### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by MiPa12** [karray/neuroracer#3]
Hi, I try to use your package. I got this error: 

File "/home/user/.local/lib/python2.7/site-packages/gym/envs/registration.py", line 18, in load
AttributeError: 'module' object has no attribute 'tasks.neuroracer_continuous_task.NeuroracerContinuousTask'

[neuroracer_gym_rl-1] process has died [pid 21541, exit code 1, cmd /home/user/catkin_ws/src/neuroracer/neuroracer_gym_rl/scripts/ddpg.py __name:=neuroracer_gym_rl __log:=/home/user/.ros/log/0979c684-993e-11ea-8ca4-e454e86c165e/neuroracer_gym_rl-1.log].
log file: /home/user/.ros/log/0979c684-993e-11ea-8ca4-e454e86c165e/neuroracer_gym_rl-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Do I have to change something in registration.py? any tip will be appreciated, thank you

**Comment by karray** [comment]
Hi, sorry for the late answer. It seems you have problems with Gym itself. I assume you have the latest version of Gym. Try to install 0.10.9. You can find the requirements [here](https://github.com/karray/neuroracer/blob/master/docker/requirements.txt)
